version: '3.5'

networks:
  hls-network:
    driver: bridge

services:
  api:
    container_name: home-library-service
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    env_file:
      - .env
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    networks:
      - hls-network
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - hls-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${PORT_DB}:${PORT_DB}
    networks:
      - hls-network

volumes:
  hls-postgres:
